[memory.flash]
size = "1M"
origin = 0x00000000

[memory.ram]
size = "256K"
origin = 0x20000000

[heap.main]
size = "128K"
pools = [
    { block = "4", capacity = 1511 },
    { block = "36", capacity = 415 },
    { block = "216", capacity = 96 },
    { block = "644", capacity = 39 },
    { block = "1412", capacity = 17 },
    { block = "2600", capacity = 8 },
    { block = "4292", capacity = 3 },
    { block = "6556", capacity = 1 },
]

[linker]
platform = "arm"

[probe]
gdb-client-command = "gdb-multiarch"

[probe.jlink]
gdb-server-command = "JLinkGDBServerCLExe"
commander-command = "JLinkExe"
device = "NRF9160"
interface = "SWD"
speed = 4000
port = 2331

[log.dso]
baud-rate = 115200
serial-endpoint = "/dev/ttyACM0"
